apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: config-server-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - config-server
  template:
    metadata:
      name: config-server
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: hubbjo/config-server
          ports:
          - containerPort: 8888
            protocol: TCP
          livenessProbe:
            httpGet:
              # This gives a http 503 if the server is down
              #       path: /actuator/health
              path: /actuator
              port: 8888
